### ISSUE TITLE
Add section on contact page on how to delete user accounts

### ISSUE THREAD

**Issue by bshapiro** [BusPeopleMedia/landing-page#2]
This is required by Google. 

![Image](https://user-images.githubusercontent.com/1351978/250307617-ad7413ec-0d26-466c-a780-f546a011a58f.png)

**Comment by attali-david** [comment]
![Image](https://github.com/BusPeopleMedia/landing-page/assets/84137250/340078a0-3836-4ccd-900e-298697ef8315)
